# Generated by Django 4.2 on 2023-04-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_author_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'komentár', 'verbose_name_plural': 'komentáre'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'príspevok', 'verbose_name_plural': 'príspevky'},
        ),
    ]
