# Generated by Django 4.1.7 on 2023-03-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_category_clazz_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIToken',
            fields=[
                ('token_hash', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
