# Generated by Django 4.1.7 on 2023-03-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userapitoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAPIToken',
            new_name='UserToken',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='token_hash',
            new_name='token',
        ),
    ]
