# Generated by Django 4.1.7 on 2023-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Specifies whether the user has admin privileges. Has more privileges than regular staff but not as much as superuser.'),
        ),
    ]
