# Generated by Django 4.1.7 on 2023-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='permission_group',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Specifies whether the user has admin privileges. Has more privileges than regular staff but not as much as superuser.', verbose_name='admin'),
        ),
    ]
