version: '3.4'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=psql://postgres:postgres@db/postgres
    env_file:
      - .env
    command: "./entrypoint.sh dev"

volumes:
  postgres_data:
