# Generated by Django 4.2 on 2023-04-03 18:51

import disciplines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0006_result_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='volatile_date',
            field=models.BooleanField(default=False, help_text='If checked, an alert will be displayed that the date and time of the discipline may change.'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.CharField(default=disciplines.models.gen_id, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
