# Generated by Django 4.2 on 2023-04-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_clazz_options_alter_grade_options_and_more'),
        ('disciplines', '0007_discipline_volatile_date_alter_discipline_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategória', 'verbose_name_plural': 'kategórie'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'umiestnenie', 'verbose_name_plural': 'umiestnenia'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'výsledkovka', 'verbose_name_plural': 'výsledkovky'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tagy'},
        ),
        migrations.AddField(
            model_name='result',
            name='grades',
            field=models.ManyToManyField(blank=True, help_text='Stupne z ktorých triedy sa mali v disciplíne zúčastniť.', to='users.grade', verbose_name='Stupne'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.category', verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Detaily'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Miesto'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tagy, ktoré sa zobrazia pri disciplíne. Kategória a stupne sú pridané automaticky.', to='disciplines.tag', verbose_name='Tagy'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='target_grades',
            field=models.ManyToManyField(blank=True, to='users.grade', verbose_name='Cielené stupne'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Čas'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='volatile_date',
            field=models.BooleanField(default=False, help_text='Ak je zaškrtnuté, zobrazí sa varovanie, že dátum sa ešte môže zmeniť.', verbose_name='Neurčitý dátum'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz', verbose_name='Trieda'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='place',
            field=models.PositiveSmallIntegerField(default=-1, verbose_name='Pozícia'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.result', verbose_name='Výsledkovka'),
        ),
        migrations.AlterField(
            model_name='result',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.discipline', verbose_name='Disciplína'),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(blank=True, help_text='Zobrazí sa ak sú k disciplíne priradené viaceré výsledkovky.', max_length=100, null=True, verbose_name='Názov výsledkovky'),
        ),
        migrations.AlterField(
            model_name='result',
            name='placements',
            field=models.ManyToManyField(through='disciplines.Placement', to='users.clazz', verbose_name='Umiestnenia'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Názov'),
        ),
    ]
