# Generated by Django 4.2 on 2023-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_authrestrictions_authrestriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authrestriction',
            name='enabled',
        ),
        migrations.AddField(
            model_name='authrestriction',
            name='restricted',
            field=models.BooleanField(default=True, help_text='Whether this restriction is enabled.'),
        ),
    ]
