# Generated by Django 4.2 on 2023-04-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_authrestriction_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrestriction',
            name='message',
            field=models.CharField(blank=True, help_text='Message to be displayed when this restriction is active.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='authrestriction',
            name='bypass_ip',
            field=models.CharField(blank=True, help_text='Specific IP address which can bypass this restriction. Multiple can be separated by commas.', max_length=1000),
        ),
    ]
