# Generated by Django 4.2.1 on 2023-05-23 06:57

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_authrestriction_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(default=data.models.gen_id, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('type', models.CharField(choices=[('success', 'Úspešné'), ('info', 'Informácia'), ('warning', 'Varovanie'), ('error', 'Chyba')])),
                ('show_on_site', models.BooleanField(default=True)),
                ('show_in_admin', models.BooleanField(default=True)),
            ],
        ),
    ]
