# Generated by Django 4.2.1 on 2023-05-23 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='lasts_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
