# Generated by Django 4.2.1 on 2023-05-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alert_active_alert_created_at_alert_lasts_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='title',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='content',
        ),
    ]
