# Generated by Django 4.2.1 on 2023-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_title_alert_message_remove_alert_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='exposed',
            field=models.BooleanField(default=False, help_text='Whether this setting is exposed to the API.'),
        ),
    ]
