# Generated by Django 4.2.1 on 2023-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_authrestriction_bypass_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditPermissions',
            fields=[
                ('user_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.BooleanField(default=False)),
                ('first_name', models.BooleanField(default=False)),
                ('last_name', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('phone_number', models.BooleanField(default=False)),
                ('password', models.BooleanField(default=False)),
            ],
        ),
    ]
