# Generated by Django 4.2.1 on 2023-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_authrestriction_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrestriction',
            name='full',
            field=models.BooleanField(default=False, help_text='Whether this restriction applies to all users. This setting effectively disables all bypasses.'),
        ),
    ]
