# Generated by Django 4.2.1 on 2023-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_hueytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileeditpermissions',
            name='discord_id',
            field=models.BooleanField(default=False),
        ),
    ]
