# Generated by Django 4.2.4 on 2023-09-16 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_clazz_microsoft_department'),
        ('data', '0014_profileeditpermissions_discord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('target', models.CharField(blank=True, max_length=500, null=True)),
                ('requires_login', models.BooleanField(default=False)),
                ('requires_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinkClassTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=500)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_targets', to='data.link')),
            ],
            options={
                'verbose_name': 'link pre triedu',
                'verbose_name_plural': 'linky pre triedy',
                'unique_together': {('link', 'clazz')},
            },
        ),
    ]
