"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from django.utils import timezone
import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

SECRET_KEY = env(
    "SECRET_KEY", default="django-insecure-g)d0f!f@6r&^e!y!)4rxosy=aczx1&)1+vt8ysevp7ajps#m14"
)
DEBUG = env("DEBUG", default=False)

if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://localhost:5173",
        "https://2023.oh.gamca.sk",
        "https://oh.gamca.sk",
        "https://oh.jaksia.xyz",
    ]
else:
    CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", default=[])

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = env("ALLOWED_HOSTS", default=[])

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS", default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend.users',
    'backend.disciplines',
    'backend.posts',
    'backend.ciphers',
    'backend.kalendar',
    'backend.data',
    'admin.apps.OHGamcaAdminConfig',
    'rest_framework',
    'knox',
    'django_filters',
    'django_admin_logs',
    'mdeditor',
    'corsheaders',
    'adminsortable2',
    'django_extensions',
    'django_probes',
    'phonenumber_field',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'backend.urls'
DJANGO_ADMIN_LOGS_DELETABLE = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": env.db()
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'sk-sk'

TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'admin_static/'
STATICFILES_DIRS = [BASE_DIR / 'backend' / 'static']

DEFAULT_FILE_STORAGE = 'backend.storages.OverwriteFileSystemStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

MDEDITOR_CONFIGS = {
    'default': {
        'width': '100% ',  # Custom edit box width
        'height': 700,  # Custom edit box height
        'toolbar': ["undo", "redo", "|",
                    "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
                    "h1", "h2", "h3", "h5", "h6", "|",
                    "list-ul", "list-ol", "hr", "|",
                    "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
                    "emoji", "html-entities", "pagebreak", "goto-line", "|",
                    "help", "info",
                    "||", "preview", "watch", "fullscreen"],  # custom edit box toolbar
        # image upload format type
        'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp", "svg"],
        'image_folder': 'editor',  # image save the folder name
        'theme': 'default',  # edit box theme, dark / default
        'preview_theme': 'default',  # Preview area theme, dark / default
        'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
        'toolbar_autofixed': False,  # Whether the toolbar capitals
        'search_replace': True,  # Whether to open the search for replacement
        'emoji': True,  # whether to open the expression function
        'tex': True,  # whether to open the tex chart function
        'flow_chart': True,  # whether to open the flow chart function
        'sequence': True,  # Whether to open the sequence diagram function
        'watch': True,  # Live preview
        'lineWrapping': True,  # lineWrapping
        'lineNumbers': True,  # lineNumbers
        'language': 'en'  # zh / en / es
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'PAGE_SIZE': 1000,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.AdminRenderer'
    ]
}

REST_KNOX = {
    'TOKEN_TTL': timedelta(days=7),
    'AUTO_REFRESH': False,
    'AUTH_HEADER_PREFIX': 'Bearer',
}

CIPHERS_MAX_FILE_SIZE = 1024 * 1024 * 10  # 10 MB
CIPHERS_ALLOWED_FILE_TYPES = ['.pdf', '.txt', '.jpg', '.jpeg', '.png']

CSP_DEFAULT_SRC = ("'self'", "localhost:5173/", "localhost/", "localhost:8000/", "127.0.0.1:5173/", "127.0.0.1/", "127.0.0.1:8000/",
                   "https://*.google.com/", "https://*.googleapis.com/", "https://*.gstatic.com/", "https://*.google-analytics.com/",
                   "https://*.googletagmanager.com/")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "localhost:5173/", "localhost/", "localhost:8000/", "127.0.0.1:5173/", "127.0.0.1/",
                 "127.0.0.1:8000/", "https://oh.gamca.sk/", "https://2023.oh.gamca.sk/", "https://oh.jaksia.xyz/")
CSP_FRAME_SRC = ("'self'", "localhost:5173/", "localhost/", "localhost:8000/", "127.0.0.1:5173/", "127.0.0.1/", "127.0.0.1:8000/",
                 "https://oh.gamca.sk/", "https://2023.oh.gamca.sk/", "https://oh.jaksia.xyz/")

PHONENUMBER_DB_FORMAT = 'E164'
PHONENUMBER_DEFAULT_REGION = 'SK'
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL'

OAUTH_APP_ID = env("OAUTH_APP_ID", default="b4c732ad-f922-452d-8515-633faccca296")
OAUTH_REDIRECT = env("OAUTH_REDIRECT", default="http://localhost:8000/api/auth/callback")
OAUTH_FE_REDIRECT = env("OAUTH_DE_REDIRECT", default="http://localhost:5173/auth/login")
OAUTH_APP_SECRET = env("OAUTH_APP_SECRET")

OAUTH_ADMIN_REDIRECT = env("OAUTH_ADMIN_REDIRECT", default="http://localhost:8000/api/auth/admin/callback")
OAUTH_ADMIN_LOGOUT = env("OAUTH_ADMIN_LOGOUT", default="http://localhost:8000/admin/logout")
OAUTH_ADMIN_LOGIN_URL = env("OAUTH_ADMIN_LOGIN_URL", default="http://localhost:8000/api/auth/admin/login")
OAUTH_ADMIN_LOGIN_REDIRECT = env("OAUTH_ADMIN_LOGIN_REDIRECT", default="http://localhost:8000/admin")
