"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import hashlib
import os
from datetime import timedelta
from pathlib import Path

from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-g)d0f!f@6r&^e!y!)4rxosy=aczx1&)1+vt8ysevp7ajps#m14"
)
DEBUG = bool(os.environ.get("DEBUG", False))


hosts = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if hosts:
    CSRF_TRUSTED_ORIGINS = hosts.split(",")
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = ["*"]

hosts = os.environ.get("ALLOWED_HOSTS", "")
if hosts:
    ALLOWED_HOSTS = hosts.split(",")
elif DEBUG:
    ALLOWED_HOSTS = ["*"]

hosts = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if hosts:
    CORS_ALLOWED_ORIGINS = hosts.split(",")
elif DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'disciplines.apps.DisciplinesConfig',
    'posts.apps.PostsConfig',
    'ciphers.apps.CiphersConfig',
    'kalendar.apps.CalendarConfig',
    'data.apps.DataConfig',
    # 'jet.dashboard',
    # 'jet',
    'admin.apps.OHGamcaAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'knox',
    'django_filters',
    'django_admin_logs',
    'mdeditor',
    'corsheaders',
    'adminsortable2',
    'django_extensions',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'
DJANGO_ADMIN_LOGS_DELETABLE = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "postgres"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "db"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'sk-sk'

TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'admin_static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'uploads'
MEDIA_URL = '/uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

MDEDITOR_CONFIGS = {
    'default': {
        'width': '100% ',  # Custom edit box width
        'height': 700,  # Custom edit box height
        'toolbar': ["undo", "redo", "|",
                    "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
                    "h1", "h2", "h3", "h5", "h6", "|",
                    "list-ul", "list-ol", "hr", "|",
                    "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
                    "emoji", "html-entities", "pagebreak", "goto-line", "|",
                    "help", "info",
                    "||", "preview", "watch", "fullscreen"],  # custom edit box toolbar
        # image upload format type
        'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp", "svg"],
        'image_folder': 'editor',  # image save the folder name
        'theme': 'default',  # edit box theme, dark / default
        'preview_theme': 'default',  # Preview area theme, dark / default
        'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
        'toolbar_autofixed': False,  # Whether the toolbar capitals
        'search_replace': True,  # Whether to open the search for replacement
        'emoji': True,  # whether to open the expression function
        'tex': True,  # whether to open the tex chart function
        'flow_chart': True,  # whether to open the flow chart function
        'sequence': True,  # Whether to open the sequence diagram function
        'watch': True,  # Live preview
        'lineWrapping': True,  # lineWrapping
        'lineNumbers': True,  # lineNumbers
        'language': 'en'  # zh / en / es
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.AdminRenderer'
    ]
}

REST_KNOX = {
    'TOKEN_TTL': timedelta(days=7),
    'AUTO_REFRESH': False,
    'AUTH_HEADER_PREFIX': 'Bearer',
}

# Add this to your settings.py to customize applications and models list
JET_SIDE_MENU_ITEMS = [
    {'label': 'Administrácia', 'app_label': 'data', 'items': [
        {'name': 'authrestriction', 'label': 'Obmedzenia prihlasovania'},
        {'name': 'setting', 'label': 'Nastavenia'},
        {'name': 'admin.logentry', 'label': 'Logy', 'url': {
            'type': 'reverse',
            'name': 'admin:admin_logentry_changelist',
        }}
    ]},
    {'label': 'Disciplíny', 'app_label': 'disciplines', 'items': [
        {'name': 'discipline'},
        {'name': 'result'},
        {'name': 'category'},
    ]},
    {'label': 'Príspevky', 'app_label': 'posts', 'items': [
        {'name': 'post'},
        {'name': 'comment'},
        {'name': 'tag'},
    ]},
    {'label': 'Šifry', 'app_label': 'ciphers', 'items': [
        {'name': 'cipher'},
        {'name': 'submission'},
    ]},
    {'label': 'Kalendár', 'app_label': 'kalendar', 'items': [
        {'name': 'calendar', 'label': 'Dáta kalendára'},
        {'name': 'generationevent', 'label': 'Záznamy generovania'},
    ]},
    {'label': 'Používatelia', 'app_label': 'users', 'items': [
        {'name': 'user'},
        {'name': 'microsoftuser'},
        {'name': 'grade'},
        {'name': 'clazz'},
        {'name': 'knox.authtoken', 'label': 'Prístupové kľúče'},
        {'name': 'auth.group', 'label': 'Skupiny'},
    ]},
]

CIPHERS_DELAY = timezone.timedelta(minutes=15)
CIPHERS_MAX_FILE_SIZE = 1024 * 1024 * 10  # 10 MB
CIPHERS_ALLOWED_FILE_TYPES = ['.pdf', '.txt', '.jpg', '.jpeg', '.png']
