# Generated by Django 4.1.5 on 2023-02-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date_published', models.BooleanField(default=False)),
                ('description_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(default=-1)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='disciplines.discipline')),
                ('placements', models.ManyToManyField(through='disciplines.Placement', to='users.clazz')),
            ],
        ),
        migrations.AddField(
            model_name='placement',
            name='results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.results'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='tags',
            field=models.ManyToManyField(blank=True, to='disciplines.tag'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='target_categories',
            field=models.ManyToManyField(blank=True, to='users.category'),
        ),
    ]
