# Generated by Django 4.1.5 on 2023-02-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='placements',
            field=models.ManyToManyField(through='disciplines.Placement', to='users.clazz'),
        ),
        migrations.AddField(
            model_name='placement',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz'),
        ),
        migrations.AddField(
            model_name='placement',
            name='results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.results'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='tags',
            field=models.ManyToManyField(blank=True, to='disciplines.tag'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='target_categories',
            field=models.ManyToManyField(blank=True, to='users.category'),
        ),
    ]
