# Generated by Django 4.2 on 2023-04-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0008_alter_category_options_alter_placement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='tags',
        ),
    ]
