# Generated by Django 4.2 on 2023-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0011_alter_result_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='place',
            field=models.SmallIntegerField(default=-1, verbose_name='Pozícia'),
        ),
    ]
