# Generated by Django 4.2 on 2023-04-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_grade_competing'),
        ('disciplines', '0012_alter_placement_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='description_published',
        ),
        migrations.RemoveField(
            model_name='result',
            name='placements',
        ),
        migrations.AddField(
            model_name='discipline',
            name='details_published',
            field=models.BooleanField(default=False, verbose_name='Detaily zverejnené'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='date_published',
            field=models.BooleanField(default=False, verbose_name='Dátum zverejnený'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='results_published',
            field=models.BooleanField(default=False, verbose_name='Výsledky zverejnené'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='target_grades',
            field=models.ManyToManyField(blank=True, limit_choices_to={'competing': True}, to='users.grade', verbose_name='Cielené stupne'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='users.clazz', verbose_name='Trieda'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='disciplines.result', verbose_name='Výsledkovka'),
        ),
    ]
