# Generated by Django 4.2 on 2023-05-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0013_remove_discipline_description_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='calendar_class',
            field=models.CharField(blank=True, help_text='CSS trieda, ktorá sa priradí k disciplínam tejto kategórie v kalendári.', max_length=100, null=True, verbose_name='CSS trieda'),
        ),
    ]
