# Generated by Django 4.2 on 2023-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0014_category_calendar_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='short_name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Krátky názov'),
        ),
    ]
