# Generated by Django 4.2 on 2023-05-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0015_discipline_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='short_name',
            field=models.CharField(blank=True, help_text='Zobrazí sa v kalendári. Maximálna dĺžka ktorá sa v kalebdári správne zobrazí je 15 znakov. V prípade viac ako 3 disciplín v jednom dni odporúčame maximálne 7 znakov.', max_length=15, null=True, verbose_name='Krátky názov'),
        ),
    ]
