# Generated by Django 4.2 on 2023-05-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0017_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='details_post',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='results_post',
        ),
    ]
