# Generated by Django 4.2.1 on 2023-05-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0019_alter_discipline_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'permissions': [('publish_date', 'Can publish date'), ('publish_details', 'Can publish details'), ('publish_results', 'Can publish results')]},
        ),
    ]
