# Generated by Django 4.2.1 on 2023-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0020_alter_discipline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['place'], 'verbose_name': 'umiestnenie', 'verbose_name_plural': 'umiestnenia'},
        ),
        migrations.AddField(
            model_name='placement',
            name='participated',
            field=models.BooleanField(default=False, verbose_name='Zúčastnil sa'),
        ),
    ]
