# Generated by Django 4.2.1 on 2023-05-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0021_alter_placement_options_placement_participated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='participated',
            field=models.BooleanField(default=False, verbose_name='Zúčastnili sa'),
        ),
    ]
