# Generated by Django 4.2.1 on 2023-05-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0022_alter_placement_participated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='participated',
        ),
    ]
