# Generated by Django 4.2.1 on 2023-05-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0023_remove_placement_participated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'umiestnenie', 'verbose_name_plural': 'umiestnenia'},
        ),
    ]
