# Generated by Django 4.2.1 on 2023-06-04 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0026_alter_discipline_teacher_oversight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'permissions': [('publish_date', 'Can publish date'), ('publish_details', 'Can publish details'), ('publish_results', 'Can publish results'), ('modify_people', 'Can modify organizers and supervisors')]},
        ),
        migrations.RenameField(
            model_name='discipline',
            old_name='teacher_oversight',
            new_name='teacher_supervisors',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='organizers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'clazz__grade__is_organizer': True}, related_name='organized_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Organizátori'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='primary_organizer',
            field=models.ForeignKey(blank=True, limit_choices_to={'clazz__grade__is_organizer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Zodpovedný organizátor'),
        ),
    ]
