# Generated by Django 4.2.1 on 2023-06-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0027_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'permissions': [('publish_date', 'Can publish date'), ('publish_details', 'Can publish details'), ('publish_results', 'Can publish results'), ('modify_people', 'Can modify organisers and supervisors')]},
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='primary_organizer',
        ),
        migrations.AddField(
            model_name='discipline',
            name='organisers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'clazz__grade__is_organiser': True}, related_name='organized_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Organizátori'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='primary_organiser',
            field=models.ForeignKey(blank=True, limit_choices_to={'clazz__grade__is_organiser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Zodpovedný organizátor'),
        ),
    ]
