# Generated by Django 4.2.1 on 2023-06-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0029_remove_discipline_organisers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='volatile_date',
        ),
    ]
