# Generated by Django 4.2.1 on 2023-08-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0032_alter_discipline_primary_organisers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'permissions': [('publish_date', 'Can publish date'), ('publish_details', 'Can publish details'), ('publish_results', 'Can publish results'), ('hide_published', 'Can hide published data'), ('modify_people', 'Can modify organisers and supervisors'), ('view_hidden', 'Can view disciplines that are not public'), ('view_primary_organisers', 'Can view primary organisers'), ('view_teacher_supervisors', 'Can view teacher supervisors')]},
        ),
    ]
