# Generated by Django 4.2.4 on 2023-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0033_alter_discipline_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='time',
        ),
        migrations.AddField(
            model_name='discipline',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Čas konca'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Čas začiatku'),
        ),
    ]
