# Generated by Django 4.2.4 on 2023-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0034_remove_discipline_time_discipline_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Ikona, ktorá sa zobrazí v navbare. Používa sa Iconify.', max_length=100, null=True, verbose_name='Ikona'),
        ),
    ]
