# Generated by Django 4.2.4 on 2023-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0034_remove_discipline_time_discipline_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='short_name',
            field=models.CharField(blank=True, help_text='Zobrazí sa v kalendári. Odporúča sa použiť ak je názov príliš dlhý a do kalendára by sa nezmestil (resp. bol odseknutý).', max_length=30, null=True, verbose_name='Krátky názov'),
        ),
    ]
