# Generated by Django 4.2.4 on 2023-09-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0035_alter_discipline_short_name'),
        ('disciplines', '0036_alter_discipline_details'),
    ]

    operations = [
    ]
