# Generated by Django 4.2.4 on 2023-10-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0040_discipline_teacher_supervisors_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='detail',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Detaily'),
        ),
    ]
