# Generated by Django 4.2 on 2023-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0004_calendar_id_calendar_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationevent',
            name='was_successful',
            field=models.BooleanField(default=False),
        ),
    ]
