# Generated by Django 4.1.5 on 2023-02-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciphers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='clazz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz'),
        ),
    ]
