# Generated by Django 4.1.5 on 2023-02-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('task_file', models.FileField(upload_to='ciphers/tasks/')),
                ('visible', models.BooleanField(default=False)),
                ('hint_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('hint_file', models.FileField(blank=True, null=True, upload_to='ciphers/hints/')),
                ('hint_publish_time', models.DateTimeField(blank=True, null=True)),
                ('hint_visible', models.BooleanField(default=False)),
                ('correct_answer', models.CharField(max_length=20)),
                ('end', models.DateTimeField()),
                ('has_ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('after_hint', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciphers.cipher')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz')),
            ],
        ),
    ]
