# Generated by Django 4.2 on 2023-05-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cipher',
            name='hint_file',
        ),
    ]
