# Generated by Django 4.2.1 on 2023-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0005_remove_cipher_has_ended_remove_cipher_hint_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='submission_delay',
            field=models.IntegerField(default=600, help_text='Čas v sekundách, ktorý musí uplynúť pred odoslanímďalšej odpovede. Predvolená hodnota je 600 sekúnd(10 minút), odporúčame nemeniť.', verbose_name='Interval medzi odpoveďami'),
        ),
    ]
