# Generated by Django 4.2.1 on 2023-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0006_cipher_submission_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipher',
            name='submission_delay',
            field=models.IntegerField(default=600, help_text='Čas v sekundách, ktorý musí uplynúť pred odoslanímďalšej odpovede. Predvolená hodnota je 600 sekúnd(10 minút), odporúčame nemeniť. Pri individuálnom riešení je táto hodnota zdvojnásobená.', verbose_name='Interval medzi odpoveďami'),
        ),
    ]
