# Generated by Django 4.2.1 on 2023-06-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0007_alter_cipher_submission_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='ignore_accents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cipher',
            name='ignore_case',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cipher',
            name='ignore_whitespace',
            field=models.BooleanField(default=True),
        ),
    ]
