# Generated by Django 4.2.1 on 2023-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0008_cipher_ignore_accents_cipher_ignore_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cipher',
            name='ignore_whitespace',
        ),
        migrations.AddField(
            model_name='cipher',
            name='ignore_intermediate_whitespace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cipher',
            name='ignore_trailing_leading_whitespace',
            field=models.BooleanField(default=True),
        ),
    ]
