# Generated by Django 4.2.1 on 2023-06-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0010_alter_cipher_submission_delay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cipher',
            options={'permissions': [('change_cipher_advanced', 'Úprava pokročilých nastavení šifry')], 'verbose_name': 'šifra', 'verbose_name_plural': 'šifry'},
        ),
    ]
