# Generated by Django 4.2.4 on 2023-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0011_alter_cipher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher',
            name='max_submissions_per_day',
            field=models.IntegerField(default=5, help_text='Maximálny počet odpovedí na túto šifru za deň.'),
        ),
    ]
