# Generated by Django 4.2.4 on 2023-10-04 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_clazz_microsoft_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciphers', '0012_cipher_max_submissions_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=3)),
                ('detail', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciphers.cipher')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clazz')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=3)),
                ('detail', models.CharField(blank=True, max_length=2000, null=True)),
                ('revision', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciphers.rating')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
