# Generated by Django 4.2.4 on 2023-10-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphers', '0013_rating_ratinghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratinghistory',
            options={'ordering': ['-created'], 'verbose_name': 'rating history entry', 'verbose_name_plural': 'rating history entries'},
        ),
    ]
