# Generated by Django 4.1.7 on 2023-03-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='affected_categories',
            new_name='affected_grades',
        ),
    ]
