# Generated by Django 4.2 on 2023-05-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Názov')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tagy',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts_for_tag', to='posts.tag', verbose_name='Tagy'),
        ),
    ]
