# Generated by Django 4.2 on 2023-05-14 07:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(max_length=10000, verbose_name='Obsah'),
        ),
    ]
