# Generated by Django 4.2.1 on 2023-06-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_tag_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disable_comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
