# Generated by Django 4.2.1 on 2023-06-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='redirect',
            field=models.CharField(blank=True, help_text='Presmerovanie na inú stránku. Ak je vyplnené, obsah bude ignorovaný.', max_length=100, null=True, verbose_name='Presmerovanie'),
        ),
    ]
