# Generated by Django 4.2.4 on 2023-08-30 18:09

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(max_length=20000, verbose_name='Obsah'),
        ),
    ]
