# Generated by Django 4.2.4 on 2023-09-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('change_others_post', 'Can change posts of other users'), ('delete_others_post', 'Can delete posts of other users'), ('post_as_other', 'Can post as other user')], 'verbose_name': 'príspevok', 'verbose_name_plural': 'príspevky'},
        ),
    ]
