# Generated by Django 4.2.4 on 2023-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='safe',
            field=models.BooleanField(default=False, help_text='Ak je zapnuté, v obsahu bude možné použiť kompletné HTML. Iba admin vie meniť.', verbose_name='Bezpečné'),
        ),
    ]
