# Generated by Django 4.1.7 on 2023-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usertoken_last_ip_remove_usertoken_last_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('2. Stupeň', '2. Stupeň'), ('3. Stupeň', '3. Stupeň'), ('Organizátori', 'Organizátori'), ('Učitelia', 'Učitelia')], max_length=100, unique=True),
        ),
    ]
