# Generated by Django 4.2 on 2023-05-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_grade_competing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
