# Generated by Django 4.2 on 2023-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cipher_competing',
            field=models.BooleanField(default=False, verbose_name='Súťaží v online šifrovačke?'),
        ),
    ]
