# Generated by Django 4.2.1 on 2023-05-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_grade_cipher_competing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clazz',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.grade', verbose_name='Stupeň'),
        ),
    ]
