# Generated by Django 4.2.1 on 2023-06-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_grade_is_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='is_organizer',
            new_name='is_organiser',
        ),
    ]
