# Generated by Django 4.2.1 on 2023-06-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_is_organizer_grade_is_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual_cipher_solving',
            field=models.BooleanField(default=False, verbose_name='Rieši šifrovačku individuálne'),
        ),
    ]
