# Generated by Django 4.2.1 on 2023-06-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0022_alter_user_individual_cipher_solving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='grade',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='individual_cipher_solving',
            field=models.BooleanField(default=False, help_text='Používateľ môže riešiť šifrovačku individuálne, bez priradenia do triedy. Ak trieda používateľa súťaží v online šifrovačke, táto možnosť nemá žiadny efekt.', verbose_name='Môže riešiť šifrovačku individuálne'),
        ),
    ]
