# Generated by Django 4.2.1 on 2023-06-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_is_admin_grade_permission_group_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
