# Generated by Django 4.2.1 on 2023-08-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='Discord ID'),
        ),
    ]
