# Generated by Django 4.2.4 on 2023-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='Je organizátorská'),
        ),
    ]
