# Generated by Django 4.2 on 2023-04-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='fulfill_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='kalendar.generationevent'),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
