# Generated by Django 4.2 on 2023-04-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0002_generationrequest_fulfill_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generationevent',
            old_name='initiation_reason',
            new_name='cause',
        ),
        migrations.DeleteModel(
            name='GenerationRequest',
        ),
    ]
