# Generated by Django 4.2 on 2023-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0003_rename_initiation_reason_generationevent_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generationevent',
            name='generated_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
