# Generated by Django 4.2.4 on 2023-08-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0005_generationevent_was_successful'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'default_permissions': ('view',), 'permissions': [('view_all', 'Can view all calendars')]},
        ),
    ]
