# Generated by Django 4.2.4 on 2023-08-24 10:15

import backend.kalendar.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0034_remove_discipline_time_discipline_end_time_and_more'),
        ('kalendar', '0006_alter_calendar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=backend.kalendar.models.gen_id, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Názov')),
                ('start_date', models.DateField(verbose_name='Dátum začiatku')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Čas začiatku')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Dátum konca')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Čas konca')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Miesto')),
                ('only_staff', models.BooleanField(default=False, verbose_name='Viditeľné len s dodatočným povolením')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.category', verbose_name='Kategória')),
            ],
        ),
    ]
