# Generated by Django 4.2.4 on 2023-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0007_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='Preferovane nepoužívať, nie je dobre podporované v kalendári.', null=True, verbose_name='Dátum konca'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default="00:00:00", verbose_name='Čas začiatku'),
            preserve_default=False,
        ),
    ]
