# Generated by Django 4.2.4 on 2023-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0008_alter_event_end_date_alter_event_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
