# Generated by Django 4.2.4 on 2023-12-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0042_result_categories_alter_discipline_category_and_more'),
        ('kalendar', '0009_rename_start_date_event_date_remove_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplines.category', verbose_name='Kategória'),
        ),
    ]
